In [1]:
import numpy as np

In [2]:
arr = np.arange(9)

In [4]:
arr.shape

(9,)

In [5]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr2 = np.arange(9,18)

In [7]:
arr2.shape

(9,)

In [15]:
arr1 = arr.reshape(3,3)

In [16]:
arr3 = arr2.reshape(3,3)

In [14]:
np.dot(arr, arr2)

528

In [18]:
cross_pro = np.cross(arr1,arr3)

In [19]:
cross_pro / 9

array([[-1.,  2., -1.],
       [-1.,  2., -1.],
       [-1.,  2., -1.]])

In [21]:
np.where(arr>5)

(array([6, 7, 8], dtype=int64),)

In [22]:
arr.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
arr1.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [24]:
np.cross(arr1, arr1.T)

array([[  0,   0,   0],
       [  8, -16,   8],
       [ 16, -32,  16]])

In [27]:
arr1.nbytes

36

In [28]:
arr1.size 

9

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])